/* synthui_panel_button_types.h - types and constants for SynthUI PanelButton.
 * Header-only and LVGL-free for host testing.
 * Copyright (c) 2026 Nicholas Newdigate
 * SPDX-License-Identifier: MIT */
#ifndef SYNTHUI_PANEL_BUTTON_TYPES_H
#define SYNTHUI_PANEL_BUTTON_TYPES_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    SYNTHUI_PANEL_BUTTON_GLYPH_PLAY = 0,
    SYNTHUI_PANEL_BUTTON_GLYPH_STOP,
    SYNTHUI_PANEL_BUTTON_GLYPH_RECORD,
    SYNTHUI_PANEL_BUTTON_GLYPH_REWIND,
    SYNTHUI_PANEL_BUTTON_GLYPH_FORWARD,
    SYNTHUI_PANEL_BUTTON_GLYPH_UP,
    SYNTHUI_PANEL_BUTTON_GLYPH_DOWN,
    SYNTHUI_PANEL_BUTTON_GLYPH_BAR,
    SYNTHUI_PANEL_BUTTON_GLYPH_DOT,
    SYNTHUI_PANEL_BUTTON_GLYPH_NONE,
} synthui_panel_button_glyph_t;

#define SYNTHUI_PANEL_BUTTON_ACCENT_GREEN   0x48E070u
#define SYNTHUI_PANEL_BUTTON_ACCENT_AMBER   0xF0A030u
#define SYNTHUI_PANEL_BUTTON_ACCENT_RED     0xF04848u
#define SYNTHUI_PANEL_BUTTON_ACCENT_BLUE    0x90A8F0u
#define SYNTHUI_PANEL_BUTTON_ACCENT_PALE    0xD8F0F0u
#define SYNTHUI_PANEL_BUTTON_ACCENT_NONE    0x303048u
#define SYNTHUI_PANEL_BUTTON_ACCENT_DEFAULT SYNTHUI_PANEL_BUTTON_ACCENT_GREEN

#ifdef __cplusplus
}
#endif
#endif /* SYNTHUI_PANEL_BUTTON_TYPES_H */
